# nixpacks.toml

[phases.setup]
# Add "pip" to the list of packages to install
nixPkgs = ["python311", "pip", "git"]

[phases.install]
# This command is correct and will work once pip is installed
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "python bot.py"
