# nixpacks.toml

[phases.setup]
nixPkgs = ["python311", "git"]

[phases.install]
# Use "python -m pip" to ensure the correct pip is used
cmds = ["python -m pip install -r requirements.txt"]

[phases.start]
cmd = "python bot.py"
