# # nixpacks.toml

# [phases.setup]
# nixPkgs = ["python311", "python311Packages.pip", "git"]

# [phases.install]
# cmds = ["python -m pip install -r requirements.txt"]

[phases.start]
cmd = "python bot.py"
